services:
  ptjv-app:
    build: .
    container_name: ptjv_health_system
    ports:
      - "4460:4460"
    volumes:
      - ptjv_db_data:/app/db_folder
      - ./public:/app/public
    restart: always

volumes:
  ptjv_db_data: